-- MySQL Script generated by MySQL Workbench
-- Tue Feb 16 09:22:36 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema plan_padrino
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema plan_padrino
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `plan_padrino` DEFAULT CHARACTER SET utf8 ;
USE `plan_padrino` ;

-- -----------------------------------------------------
-- Table `plan_padrino`.`formas_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plan_padrino`.`formas_pago` (
  `id_formas_pago` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_formas_pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plan_padrino`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plan_padrino`.`personas` (
  `id_personas` INT NOT NULL AUTO_INCREMENT,
  `clase` TINYINT NOT NULL,
  `sos` INT NULL,
  `fecha_ingreso` DATE NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(60) NULL,
  `tipo_identificacion` TINYINT NULL,
  `identificacion` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `pais` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `dia_cobro` TINYINT NULL,
  `valor_pago` INT NULL,
  `periodicidad_pago` TINYINT NULL,
  `forma_pago` INT NULL,
  `foto` VARCHAR(45) NULL,
  `empresa` VARCHAR(45) NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_personas`),
  INDEX `fk_Personas_Personas_idx` (`sos` ASC),
  INDEX `fk_Personas_Formas_Pago1_idx` (`forma_pago` ASC),
  CONSTRAINT `fk_Personas_Personas`
    FOREIGN KEY (`sos`)
    REFERENCES `plan_padrino`.`personas` (`id_personas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personas_Formas_Pago1`
    FOREIGN KEY (`forma_pago`)
    REFERENCES `plan_padrino`.`formas_pago` (`id_formas_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plan_padrino`.`comedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plan_padrino`.`comedores` (
  `id_comedores` INT NOT NULL AUTO_INCREMENT,
  `departamento` VARCHAR(45) NOT NULL,
  `municipio` VARCHAR(45) NOT NULL,
  `barrio` VARCHAR(45) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_comedores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plan_padrino`.`beneficiarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plan_padrino`.`beneficiarios` (
  `id_beneficiarios` INT NOT NULL AUTO_INCREMENT,
  `programa` TINYINT NULL,
  `comedor` INT NULL,
  `tipo_beneficiario` TINYINT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `genero` TINYINT(1) NULL,
  `fecha_nacimiento` DATE NULL,
  `pais_nacimiento` VARCHAR(45) NULL,
  `departamento_nacimiento` VARCHAR(45) NULL,
  `municipio_nacimiento` VARCHAR(45) NULL,
  `tipo_identificacion` TINYINT NULL,
  `identificacion` VARCHAR(45) NULL,
  `lugar_expedicion` VARCHAR(45) NULL,
  `fecha_expedicion` DATE NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `municipio_residencia` VARCHAR(45) NULL,
  `fecha_ingreso` DATE NULL,
  `fase_recuperacion` TINYINT NULL,
  `donante1` TINYINT NULL,
  `donante2` TINYINT NULL,
  `donante3` TINYINT NULL,
  `nombre_institucion` VARCHAR(45) NULL,
  `nivel_estudio` TINYINT NULL,
  `estado_estudiante` TINYINT NULL,
  `jornada` TINYINT NULL,
  `grado` TINYINT NULL,
  `tipo_afiliacion_salud` TINYINT NULL,
  `entidad` VARCHAR(45) NULL,
  `carnet_familias_accion` TINYINT NULL,
  `sisben` INT NULL,
  `carnet_vacunas` TINYINT NULL,
  `control_crecimiento_desarrollo` TINYINT NULL,
  `control_prenatal` TINYINT NULL,
  `condicion_social` TINYINT NULL,
  `etnia` TINYINT NULL,
  `tipo_discapacidad` TINYINT NULL,
  `discapacidad` VARCHAR(45) NULL,
  `estado_civil` TINYINT NULL,
  `cabeza_hogar` TINYINT NULL,
  `nombre_padre` VARCHAR(45) NULL,
  `fecha_nacimiento_padre` DATE NULL,
  `nivel_estudio_padre` TINYINT NULL,
  `ocupacion_padre` VARCHAR(45) NULL,
  `direccion_padre` VARCHAR(45) NULL,
  `telefono_padre` VARCHAR(45) NULL,
  `nombre_madre` VARCHAR(45) NULL,
  `fecha_nacimiento_madre` DATE NULL,
  `nivel_estudio_madre` TINYINT NULL,
  `ocupacion_madre` VARCHAR(45) NULL,
  `direccion_madre` VARCHAR(45) NULL,
  `telefono_madre` VARCHAR(45) NULL,
  `acudiente` VARCHAR(45) NULL,
  `parentesco_acudiente` VARCHAR(45) NULL,
  `fecha_nacimiento_acudiente` DATE NULL,
  `ocupacion_acudiente` VARCHAR(45) NULL,
  `direccion_acudiente` VARCHAR(45) NULL,
  `telefono_acudiente` VARCHAR(45) NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_beneficiarios`),
  INDEX `fk_ahijados_comedores1_idx` (`comedor` ASC),
  CONSTRAINT `fk_ahijados_comedores1`
    FOREIGN KEY (`comedor`)
    REFERENCES `plan_padrino`.`comedores` (`id_comedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plan_padrino`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plan_padrino`.`pagos` (
  `id_pagos` INT NOT NULL AUTO_INCREMENT,
  `fecha_pago` VARCHAR(45) NOT NULL,
  `valor_pago` INT NOT NULL,
  `fecha_proximopago` VARCHAR(45) NOT NULL,
  `valor_proximopago` INT NOT NULL,
  `padrino` INT NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_pagos`),
  INDEX `fk_Pagos_Personas1_idx` (`padrino` ASC),
  CONSTRAINT `fk_Pagos_Personas1`
    FOREIGN KEY (`padrino`)
    REFERENCES `plan_padrino`.`personas` (`id_personas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plan_padrino`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plan_padrino`.`usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `tipo_usuario` TINYINT NOT NULL,
  `comedor` INT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_usuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plan_padrino`.`registros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plan_padrino`.`registros` (
  `id_registros` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`id_registros`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plan_padrino`.`notificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plan_padrino`.`notificaciones` (
  `id_notificaciones` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `tipo_notificacion` TINYINT NOT NULL,
  `realizado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_notificaciones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plan_padrino`.`cobros_padrinos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plan_padrino`.`cobros_padrinos` (
  `id_cobros_padrinos` INT NOT NULL AUTO_INCREMENT,
  `notificaciones_id_notificaciones` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_cobros_padrinos`),
  INDEX `fk_cobros_padrinos_notificaciones1_idx` (`notificaciones_id_notificaciones` ASC),
  CONSTRAINT `fk_cobros_padrinos_notificaciones1`
    FOREIGN KEY (`notificaciones_id_notificaciones`)
    REFERENCES `plan_padrino`.`notificaciones` (`id_notificaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plan_padrino`.`estados_beneficiarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plan_padrino`.`estados_beneficiarios` (
  `id_estados_beneficiarios` INT NOT NULL AUTO_INCREMENT,
  `ahijado` INT NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `motivo_retiro` VARCHAR(200) NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id_estados_beneficiarios`),
  INDEX `fk_estados_ahijados_ahijados1_idx` (`ahijado` ASC),
  CONSTRAINT `fk_estados_ahijados_ahijados1`
    FOREIGN KEY (`ahijado`)
    REFERENCES `plan_padrino`.`beneficiarios` (`id_beneficiarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plan_padrino`.`estados_padrinos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plan_padrino`.`estados_padrinos` (
  `id_estados_padrinos` INT NOT NULL AUTO_INCREMENT,
  `padrino` INT NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id_estados_padrinos`),
  INDEX `fk_estados_padrinos_personas1_idx` (`padrino` ASC),
  CONSTRAINT `fk_estados_padrinos_personas1`
    FOREIGN KEY (`padrino`)
    REFERENCES `plan_padrino`.`personas` (`id_personas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plan_padrino`.`personas_has_beneficiarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plan_padrino`.`personas_has_beneficiarios` (
  `personas_id_personas` INT NOT NULL,
  `beneficiarios_id_beneficiarios` INT NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`personas_id_personas`, `beneficiarios_id_beneficiarios`),
  INDEX `fk_personas_has_beneficiarios_beneficiarios1_idx` (`beneficiarios_id_beneficiarios` ASC),
  INDEX `fk_personas_has_beneficiarios_personas1_idx` (`personas_id_personas` ASC),
  CONSTRAINT `fk_personas_has_beneficiarios_personas1`
    FOREIGN KEY (`personas_id_personas`)
    REFERENCES `plan_padrino`.`personas` (`id_personas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personas_has_beneficiarios_beneficiarios1`
    FOREIGN KEY (`beneficiarios_id_beneficiarios`)
    REFERENCES `plan_padrino`.`beneficiarios` (`id_beneficiarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `plan_padrino` ;

-- -----------------------------------------------------
-- Placeholder table for view `plan_padrino`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plan_padrino`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `plan_padrino`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plan_padrino`.`view1`;
USE `plan_padrino`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
